# Numpy_Assignment_2:
    Muhammad Saad Khan

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [2]:
import numpy as np
arr1 = np.arange(10).reshape(2,5)
arr1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output:
array([[0, 1, 2, 3, 4],
         [5, 6, 7, 8, 9],
         
          [1, 1, 1, 1, 1], 
          [1, 1, 1, 1, 1]])


In [3]:
arr1
arr2 = np.ones(10).reshape(2,5)
arr2
print(arr1)
print("\n",arr2)
print("\n","stack vertical array:","\n",np.vstack((arr1,arr2)))

[[0 1 2 3 4]
 [5 6 7 8 9]]

 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

 stack vertical array: 
 [[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


## Question:3

### How to stack two arrays horizontally?

#### Desired Output:
array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1], [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [4]:
arr1
arr2
print(arr1)
print("\n",arr2)
print("\n","stack horizontal array:","\n",np.hstack((arr1,arr2)))

[[0 1 2 3 4]
 [5 6 7 8 9]]

 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

 stack horizontal array: 
 [[0. 1. 2. 3. 4. 1. 1. 1. 1. 1.]
 [5. 6. 7. 8. 9. 1. 1. 1. 1. 1.]]


## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::
array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
arr3 = np.array([[0,1,2,3,4],[5,6,7,8,9]])
print(arr3, '\n')
print(arr3.ravel())
print(arr3.flatten())

[[0 1 2 3 4]
 [5 6 7 8 9]] 

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::
array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])


In [25]:
arr4=np.array([[0,1,2],[3,4,5],[6,7,8],[9,10,11],[12,13,14]])
arr5=arr4.reshape(-1)
print(arr5)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::
array([[ 0, 1, 2], [ 3, 4, 5], [ 6, 7, 8], [ 9, 10, 11], [12, 13, 14]])


In [28]:
print(arr5,'\n')
arr5.reshape(5,3)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14] 



array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [59]:
import random
arr6=np.random.randint(100,size=(25))
x=arr6.reshape(5,5)
print(x,'\n')
print(np.square(x))

[[62 73 37 74 39]
 [74 86 65 33 50]
 [80 47 46 61 62]
 [52 82  4 19 46]
 [87 24 16 67 89]] 

[[3844 5329 1369 5476 1521]
 [5476 7396 4225 1089 2500]
 [6400 2209 2116 3721 3844]
 [2704 6724   16  361 2116]
 [7569  576  256 4489 7921]]


## Question:8

### Create 5x6 an array and find the mean?

In [65]:
arr8=np.random.randint(100,size=(30))
print(arr8)
print('\n',arr8.mean())

[14 27 74 20 77  8 58 66 96 36 28 35 51 80 13 53 60 12 45 15 83 51 65 95
 56 13 57 70 34 81]

 49.1


## Question:9

### Find the standard deviation of the previous array in Q8?

In [70]:
print(arr8)
print('\n',np.std(arr8))

[14 27 74 20 77  8 58 66 96 36 28 35 51 80 13 53 60 12 45 15 83 51 65 95
 56 13 57 70 34 81]

 26.200954181098062


## Question:10

### Find the median of the previous array in Q8?

In [71]:
print(arr8)
print('\n',np.median(arr8))

[14 27 74 20 77  8 58 66 96 36 28 35 51 80 13 53 60 12 45 15 83 51 65 95
 56 13 57 70 34 81]

 52.0


## Question:11

### Find the transpose of the previous array in Q8?

In [90]:
print(arr8)
b=np.array([arr8])
print(np.transpose(b))

[14 27 74 20 77  8 58 66 96 36 28 35 51 80 13 53 60 12 45 15 83 51 65 95
 56 13 57 70 34 81]
[[14]
 [27]
 [74]
 [20]
 [77]
 [ 8]
 [58]
 [66]
 [96]
 [36]
 [28]
 [35]
 [51]
 [80]
 [13]
 [53]
 [60]
 [12]
 [45]
 [15]
 [83]
 [51]
 [65]
 [95]
 [56]
 [13]
 [57]
 [70]
 [34]
 [81]]


## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [81]:
arr9=np.arange(16).reshape(4,4)
print(arr9)
print('\n',np.trace(arr9))


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

 30


## Question:13

### Find the determinant of the previous array in Q12?

In [84]:
print(arr9,'\n')
print(np.linalg.det(arr9))


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] 

0.0


## Question:14

### Find the 5th and 95th percentile of an array?

In [89]:
arr9
print(np.percentile(arr9,5),'\n')
print(np.percentile(arr9,95))

0.75 

14.25


## Question:15

### How to find if a given array has any null values?

In [102]:
print(arr9,'\n')
print(arr9!=0)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] 

[[False  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]
