# Assignment_1(Numpy Fundamentals) Q2 
    Muhammad Saad Khan

1. Import the numpy package under the name np

In [1]:
import numpy as np


2. Create a null vector of size 10 

In [2]:
x = np.zeros(10)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Create a vector with values ranging from 10 to 49

In [3]:
a = np.arange(10,50)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

4. Find the shape of previous array in question 3

In [4]:
np.size(a)

40

5. Print the type of the previous array in question 3

In [5]:
type(a)

numpy.ndarray

6. Print the numpy version and the configuration

In [117]:
print(np.version.version)
print(np.show_config())

1.18.1
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Saad Khan/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/Saad Khan/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Saad Khan/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\w

7. Print the dimension of the array in question 3

In [6]:
a.ndim

1

8. Create a boolean array with all the True values

In [7]:
np.ones(20, dtype=bool)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

9. Create a two dimensional array

In [8]:
b = np.array ([[1,2,3,4,5,6] , [10,11,12,13,14,15]])
b

array([[ 1,  2,  3,  4,  5,  6],
       [10, 11, 12, 13, 14, 15]])

10. Create a three dimensional array

In [9]:
c = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])
c

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

11. Reverse a vector (first element becomes last)

In [10]:
arr = [2,1,4,5]
arr.reverse()
arr

[5, 4, 1, 2]

In [11]:
arr_1  = [1,10,11,8]
d = arr_1[::-1]
d

[8, 11, 10, 1]

12. Create a null vector of size 10 but the fifth value which is 1 

In [12]:
y = np.zeros(10)
y[5] = 1
y

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

13. Create a 3x3 identity matrix

In [13]:
z = np.identity(3)
z

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [14]:
int_arr = np.array([1,2,3,4,5])
float_arr = int_arr.astype(np.float64)
float_arr

array([1., 2., 3., 4., 5.])

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2

In [15]:
arr1 = np.array([[1., 2., 3.], [4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])
arr3 = arr1 * arr2
arr3

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [16]:
arr4 = arr1 == arr2
arr4.all()
arr4

array([[False, False, False],
       [False, False, False]])

17. Extract all odd numbers from arr with values(0-9)

In [17]:
arr5 = np.arange(10)
arr5[arr5 % 2 == 1]

array([1, 3, 5, 7, 9])

18. Replace all odd numbers to -1 from previous array

In [18]:
arr5[arr5 % 2 == 1] = -1
arr5

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [19]:
arr6 = np.arange(10)
arr6[5:9] = 12
arr6

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

20. Create a 2d array with 1 on the border and 0 inside

In [20]:
arr7 = np.ones((4,4))
arr7[1:-1,1:-1] = 0
arr7

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [23]:
arr2d = np.array([[1, 2, 3],[4, 5, 6], [7, 8, 9]])
arr2d[1:-1,1:-1] = 12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64

In [27]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d.tolist()

[[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [42]:
arr8 = np.arange(10).reshape(2,5)
print(arr8)
arr8[0]

[[0 1 2 3 4]
 [5 6 7 8 9]]


array([0, 1, 2, 3, 4])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [43]:
print(arr8)
arr8[1]


[[0 1 2 3 4]
 [5 6 7 8 9]]


array([5, 6, 7, 8, 9])

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [51]:
print(arr8)
arr8[0:2,2:3]

[[0 1 2 3 4]
 [5 6 7 8 9]]


array([[2],
       [7]])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [100]:
import random
arr9 = np.random.rand(10,10)
print(arr9)
print("Minimum Value :", arr9.min())
print("Maximum Value :",arr9.max())

[[0.94049609 0.04923187 0.27983151 0.62935621 0.44966197 0.75845764
  0.5188384  0.85972467 0.02047238 0.54557207]
 [0.12536232 0.61918721 0.70928629 0.55792411 0.75552082 0.97452607
  0.81354333 0.04777185 0.22591679 0.82398091]
 [0.19681434 0.6832488  0.81597553 0.92728003 0.30695551 0.04597383
  0.79766175 0.23819452 0.68722579 0.25684535]
 [0.96010129 0.82966808 0.93015529 0.31706259 0.98999485 0.55617946
  0.90419139 0.37450512 0.73582456 0.35697027]
 [0.19432908 0.27039439 0.93550878 0.34025411 0.47349418 0.77866193
  0.12049958 0.00709696 0.7801734  0.33748099]
 [0.55253946 0.94891422 0.72302262 0.96392223 0.1900902  0.75351518
  0.29345787 0.95481081 0.67039554 0.74139395]
 [0.42868582 0.79182032 0.07378203 0.7113486  0.35592966 0.35236649
  0.86638445 0.42928556 0.29460328 0.60092707]
 [0.00409672 0.87509887 0.86503948 0.43251147 0.86309542 0.38869252
  0.93390571 0.25040654 0.64866309 0.01801011]
 [0.15088984 0.84115415 0.921606   0.86032618 0.21595304 0.11265281
  0.32008601

27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b

In [123]:
arr10 = np.array([1,2,3,2,3,4,3,4,5,6])
arr11 = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.intersect1d(arr10,arr11))

[2 4]


28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match

In [124]:
arr10 = np.array([1,2,3,2,3,4,3,4,5,6])
arr11 = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.where(arr10==arr11))

(array([1, 3, 5, 7], dtype=int32),)


29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**

In [131]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
data
print('\n',data[names!="Will"])


 [[-0.06858906  0.99407073 -1.47917396  1.31578172]
 [ 0.4248622  -1.33963162 -1.64546049 -0.08558263]
 [ 0.19165275 -0.1251559  -0.19639929 -1.25467922]
 [-0.34764402  0.79847481 -0.14700066  1.66148864]
 [ 0.09985839 -0.40483953  0.22982342 -0.76727803]]


30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**

In [134]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
data
print('\n',data[names=="Bob"])


 [[-1.20668131 -0.29883203 -0.06301947  1.77350183]
 [-1.67552032  0.23542031 -1.73979638  0.75481179]]


31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [136]:
arr12 = np.arange(1,16).reshape(5,3)
arr12

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [139]:
arr13 = np.arange(1,17,1).reshape(2,2,4)
arr13

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

33. Swap axes of the array you created in Question 32

In [147]:
print(arr13)
np.swapaxes(arr13,0,1)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]


array([[[ 1,  2,  3,  4],
        [ 9, 10, 11, 12]],

       [[ 5,  6,  7,  8],
        [13, 14, 15, 16]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [164]:
arr14 = np.random.rand(10)
print(arr14)
sqrt_arr14 = np.sqrt(arr14)
print(sqrt_arr14)
sqrt_arr14[sqrt_arr14<0.5] = 0
sqrt_arr14

    

[0.33705278 0.16805794 0.32837306 0.10869269 0.42284996 0.86425682
 0.34159399 0.80171352 0.00639889 0.22471294]
[0.58056247 0.4099487  0.57303845 0.32968575 0.65026914 0.92965414
 0.58446042 0.89538457 0.07999306 0.47403897]


array([0.58056247, 0.        , 0.57303845, 0.        , 0.65026914,
       0.92965414, 0.58446042, 0.89538457, 0.        , 0.        ])

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [210]:
arr15 = np.random.rand(12)
arr16 = np.random.rand(12)
print("\n",arr15)
print("\n",arr16)
print("\n","Maximum Array:","\n",np.maximum(arr15,arr16))


 [0.39690501 0.82797203 0.50313144 0.62252647 0.21984456 0.76809281
 0.35231875 0.90664411 0.22933193 0.22903616 0.1059941  0.20432223]

 [0.45240812 0.16854541 0.40120292 0.73842448 0.14702001 0.22455514
 0.5657922  0.62298043 0.30849596 0.74103484 0.51756223 0.26900413]

 Maximum Array: 
 [0.45240812 0.82797203 0.50313144 0.73842448 0.21984456 0.76809281
 0.5657922  0.90664411 0.30849596 0.74103484 0.51756223 0.26900413]


36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!

In [170]:
print(names)
np.unique(names)

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']


array(['Bob', 'Joe', 'Will'], dtype='<U4')

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b

In [172]:
arr17 = np.array([1,2,3,4,5])
arr18 = np.array([5,6,7,8,9])
print(np.setdiff1d(arr17,arr18))

[1 2 3 4]


38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])

In [190]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
newColumn = np.array([10,10,10])
sampleArray[:,1:2] = newColumn.reshape(3,1)
print(sampleArray)

[[34 10 73]
 [82 10 12]
 [53 10 66]]


39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix

In [194]:
arr19 = np.array([[1., 2., 3.], [4., 5., 6.]]) 
arr20 = np.array([[6., 23.], [-1, 7], [8, 9]])
np.dot(arr19,arr20)

array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [197]:
arr21 = np.random.rand(20)
print(arr21)
print(arr21.cumsum())

[0.77728757 0.24240845 0.27845743 0.8014285  0.46835047 0.85681991
 0.12522909 0.45980585 0.78281593 0.44227649 0.42968554 0.7117229
 0.07292398 0.64151847 0.88933537 0.56822956 0.5750132  0.29584023
 0.86216694 0.13182637]
[ 0.77728757  1.01969603  1.29815345  2.09958195  2.56793242  3.42475233
  3.54998142  4.00978727  4.7926032   5.23487969  5.66456523  6.37628812
  6.4492121   7.09073057  7.98006594  8.54829551  9.12330871  9.41914893
 10.28131588 10.41314225]
